### ISSUE TITLE
Using const strings instead of strings for mutation variables fails

### ISSUE THREAD

**Issue by NoTuxNoBux** [byme8/ZeroQL#108]
**Describe the bug**

When using `const string` instead of `string` for local variables, they don't seem to be passed as variables at runtime any more. The error is e.g.:

```
Variable "$username" of required type "String!" was not provided.
```

In other words, this works:

```cs
string username = "foo";
string password = "bar";

await graphQLClient.Mutation(
    q => q.AuthenticateUserWithPassword(
        username,
        password,
        x => new
        {
            ...
        }
    )
);
```

This doesn't:

```cs
const string username = "foo";
const string password = "bar";

await graphQLClient.Mutation(
    q => q.AuthenticateUserWithPassword(
        username,
        password,
        x => new
        {
            ...
        }
    )
);
```

**How to Reproduce**

1. Use a `const string` instead of a `string` during a mutation or query.

**Expected behavior**

Interpolating works the same way it does for non-const variables. Alternatively the source generator could report an error that this is not possible instead of the code failing at runtime.

(Related to this, it would also be nice if class constants were similarly supported, but I still need to alias them to a local variable and make it non-constant first.)

**The GraphqQL schema that fails**

Here is a relevant part of the schema, in case it helps:

```graphql
authenticateUserWithPassword(email: String! password: String!): UserAuthenticationWithPasswordResult

union UserAuthenticationWithPasswordResult = UserAuthenticationWithPasswordSuccess | UserAuthenticationWithPasswordFailure

type UserAuthenticationWithPasswordSuccess {
  sessionToken: String!
  item: User!
}

type UserAuthenticationWithPasswordFailure {
  message: String!
}
```

**Environment (please complete the following information):**
 - Nuget package version 6.2.1
 - IDE: VS Code
 - .Net Version: .NET Standard 2.1 (Unity)

**Comment by byme8** [comment]
From first glance, looks like it should be possible to get embed the constant value into the query. I will have a look

**Comment by byme8** [comment]
Checkout v7.0.0-preview.3. It has support for C# constants.

``` csharp
const string firstName = "John";
const string lastName = "Smith";
var response = await qlClient.Mutation(m => m.AddUser(firstName, lastName, o => o.Id));
// mutation { addUser(firstName: "John", lastName: "Smith") { id } }        
```
