### ISSUE TITLE
Automatic exceptions when queries or mutations fail

### ISSUE THREAD

**Issue by NoTuxNoBux** [byme8/ZeroQL#109]
**Is your feature request related to a problem? Please describe.**
When doing a query or mutation, I'm always following a similar pattern:

```cs
var response = await client.Mutation(...);

if (response.Errors?.Length > 0)
{
    throw new FooException($"Something went wrong during GraphQL mutation, error reported was {ParseErrorsToIncludeMessageHere(response.Errors)}");
}

if (response.Data is null)
{
    throw new BarException("No data was received, something must be wrong");
}
```

There are bits that aren't common, such as properties unique to the mutation or query being specific to it, but checking the `Data` and `Errors` properties always seems to be the same.

**Describe the solution you'd like**
It would be nice if the API client itself could automatically do this for you and throw a `GraphQLQueryFailedException` or `GraphQLMutationFailedException` or similar when these fields are set and already nicely include the messages of the API in the exception message.

This would help alleviate some boilerplate around every call.

**Describe alternatives you've considered**
1. Write the boilerplate every time.
2. Create a convenience wrapper that takes a response and creates/throws an exception if necessary.

**Additional context**
What I did now is provide an extension class:

```cs
public static class GraphQLDataExtensions
{
    /// <summary>
    /// Helper to eliminate boilerplate that needs to verify that the Data property is not null (thus representing
    /// an error) and that no GraphQL errors were returned. If verification fails, an exception is thrown.
    /// </summary>
    /// <typeparam name="TData"></typeparam>
    /// <param name="result"></param>
    /// <exception cref="GraphQLCallFailedException"></exception>
    public static void Verify<TData>(this GraphQLResult<TData> result)
    {
        if (result.Errors?.Length > 0)
        {
            string errorList = result.Errors.Select(x => x.Message).Aggregate(string.Empty, (accumulator, x) => $"{accumulator}, '{x}'").Trim(' ', ',');

            throw new GraphQLCallFailedException($"GraphQL call failed with {result.Errors.Length} error(s): {errorList}");
        }

        if (result.Data is null)
        {
            throw new GraphQLCallFailedException("GraphQL call returned no errors but failed with empty response");
        }
    }
}
```

This can then be used like so:

```cs
var response = await client.Mutation(...);

response.Verify();
```

It's still boilerplate every call, so it would be nice if `client.Mutation` and `client.Query` could do this automatically, but at least it centralizes the logic and shortens it.

What might be worth mentioning is that the OpenAPI generator generates `FooWithHttpInfoAsync` variants of every method that yield access to the full response (with headers) and don't automatically throw whilst the regular `FooAsync` methods directly return the response and fail with exceptions if necessary.

**Comment by byme8** [comment]
I don't want to add such an extension because it goes against the GraphQL philosophy. At the same time, if you need it you can use something like that:
``` csharp

public class Program
{
    public static async Task Main()
    {
        var httpClient = new HttpClient();
        httpClient.BaseAddress = new Uri("http://localhost:10000/graphql");

        var client = new ZeroQLClient(httpClient);
        var id = await client
            .MutationWithVerification(m => m
                .AddUser("John", "Doe", o => o.Id));

        Console.WriteLine(id);
    }
}

public static class GraphQLClientMutationExtensions
{
    public static async Task<T> MutationWithVerification<T, TQuery, TMutation>(
        this GraphQLClient<TQuery, TMutation> client,
        [GraphQLLambda] Func<TMutation, T> query,
        [CallerArgumentExpression(nameof(query))]
        string queryKey = "")
        where T : class
    {
        var result = await client.Mutation(query, queryKey: queryKey);

        if (result.Errors?.Length > 0)
        {
            string errorList = result.Errors.Select(x => x.Message)
                .Aggregate(string.Empty, (accumulator, x) => $"{accumulator}, '{x}'").Trim(' ', ',');

            throw new GraphQLCallFailedException(
                $"GraphQL call failed with {result.Errors.Length} error(s): {errorList}");
        }

        if (result.Data is null)
        {
            throw new GraphQLCallFailedException("GraphQL call returned no errors but failed with empty response");
        }

        return result.Data;
    }
}
```

**Comment by NoTuxNoBux** [comment]
I see. To clarify: it being slower and not always intended was why I proposed to do a similar approach to the [OpenAPI client generator](https://github.com/OpenAPITools/openapi-generator), which generates `FooWithHttpInfoAsync` variants for every `FooAsync`. The former would be what ZeroQL is currently doing: returning the full response as is, no exceptions, caller is responsible for handling everything, even HttpClient errors because 4xx or 5xx errors don't cause exceptions. The latter would automatically check the underlying `HttpClient` calls for 4xx or 5xx errors and in the case of GraphQL handles the boilerplate (checking `result.Errors`) that you almost always want to be handling anyway; if you don't you may be swallowing/hiding unintended GraphQL errors, which arguably is worse than having too many exceptions at first, since you are forced to deal with the latter but not the former.

I'll close this since extension is indeed possible from the implementor's end.
