### ISSUE TITLE
Generated client has different line endings.

### ISSUE THREAD

**Issue by DaveRMaltby** [byme8/ZeroQL#12]
When opening the generated client file in Visual Studio, I see:
![image](https://user-images.githubusercontent.com/88258058/198856922-dae6873a-177a-4c2d-8787-3a052829f81e.png)

If I take a look at the generated file in Notepad++, I see that the line endings change at the 10th line of the file:
![image](https://user-images.githubusercontent.com/88258058/198857229-c287243c-5970-4cbf-ae21-7482133a3bbb.png)

Looks like it can be fixed by changing the line endings on the string at https://github.com/byme8/ZeroQL/blob/main/src/ZeroQL.Core/Bootstrap/GraphQLGenerator.cs#L77-L86

**Comment by DavidRMaltby** [comment]
By the way, I'm happy to contribute a PR if you like.

**Comment by DaveRMaltby** [comment]
By the way, I'm happy to contribute a PR if you like.

**Comment by byme8** [comment]
Checkout [v2.1.1](https://github.com/byme8/ZeroQL/releases/tag/v2.1.1).
I removed string concatenation and replaced it via syntax tree generation. Now, this warning should go away.

> By the way, I'm happy to contribute a PR if you like.
Go ahead! You are welcome

**Comment by DaveRMaltby** [comment]
I will.  Thank you sir!
