### ISSUE TITLE
Support for default values for input objects

### ISSUE THREAD

**Issue by DaveRMaltby** [byme8/ZeroQL#17]
For a complex input object, I have GraphQL SDL of:

```
input WeightedValueOfInt32Input {
  value: Int!
  weight: Float! = 1
}
```
but the ZeroQL generated class looks like:

```
    [System.CodeDom.Compiler.GeneratedCode ( "ZeroQL" ,  "2.1.1.0" )]
    public class WeightedValueOfInt32Input
    {
        public int Value { get; set; }

        public double Weight { get; set; }
    }

```
Therefore, the `Weight` property if not specified, does not default to the value 1 as it would if you did not specify this property in a GraphQL mutation call.

**Comment by byme8** [comment]
Potentially, this feature can be useful to align generated clients with what we have in the GraohQL schema. At the same time, it is a more "nice to have" feature. It doesn't break anything.

**Comment by DaveRMaltby** [comment]
I have created PR #18 to implement this feature.
