### ISSUE TITLE
Code Generation not generating C# code for GraphQL interfaces

### ISSUE THREAD

**Issue by Victor-Linares** [byme8/ZeroQL#19]
I'm trying to use ZeroQL to generate a C# client for a graphql schema that implements interfaces for some types and the interfaces are being ignored during the code generation.
For instance, the graphql snippet below does not generates any code.

``` graphql
interface Client {
  addresses: [ClientAddress!]!
  alternateId: String
  availableCommunicationParticipants: [CommunicationParticipant!]!
  availableCommunicationTemplates: [CommunicationTemplate!]!
  bankAccounts: [BankAccount!]!
  "Provides blacklist information related to this entity."
  blacklisting: BlacklistingContext!
  claims(filters: ClaimListFiltersInput order: ClaimOrderInput = { by: CREATED, direction: DESCENDING, then: null } pagination: OptionalPaginationInput): ClaimList!
  communications(filters: CommunicationListFiltersInput order: CommunicationOrderInput = { by: CREATE_DATE, direction: DESCENDING, then: null } pagination: OptionalPaginationInput): CommunicationList!
  contactDetails: [ContactDetail!]!
  countryOfOrigin: Country
  customFields: CustomFieldContext!
  externalId: String
  id: Int!
  invoiceBatches: [ClaimPurchaseInvoiceBatch!]!
  isActive: Boolean!
  isPinned: Boolean!
  isVip: Boolean!
  language: Culture
  membershipNumber: String
  name: String!
  organisation: Organisation!
  policies(pagination: OptionalPaginationInput): PolicyList!
  purchaseInvoicesAndGuarantees(filters: ClaimPurchaseInvoiceOrPaymentGuaranteeListFiltersInput order: ClaimPurchaseInvoiceOrPaymentGuaranteeOrderInput = { by: CREATE_DATE, direction: DESCENDING, then: null } pagination: OptionalPaginationInput): ClaimPurchaseInvoiceOrPaymentGuaranteeList!
  tasks(filters: TaskListFiltersInput order: TaskOrderInput = { by: COMPLETED, direction: null, then: { by: DATE, direction: null, then: null } } pagination: OptionalPaginationInput): TaskList!
  uid: UUID!
}
```

**Comment by byme8** [comment]
I will have a look.

**Comment by byme8** [comment]
@Victor-Linares, New version [v3.1.0-preview.1](https://github.com/byme8/ZeroQL/releases/tag/v3.1.0-preview.1) has initial support for Graphql interfaces. Now It will generate interfaces and add them to appropriate classes.
The syntax for query interfaces like that is not supported yet. I am wondering how to support it.
``` graphql
query {
   users: {
      ... on IAdmin {
         canDeleteUsers
      }
   }
}
```

**Comment by byme8** [comment]
Check out [v3.2.0-preview.1](https://github.com/byme8/ZeroQL/releases/tag/v3.2.0-preview.1) for full interface support.
Examples can be found [here](https://github.com/byme8/ZeroQL#interfaces)

**Comment by byme8** [comment]
Have you had a chance to look at it?

**Comment by Victor-Linares** [comment]
Hi Stanislav,

Really appreciate your quick response on this.
I will take a look into it in the next few days and let you know about the results.

Thank you

Vitor Linares
Lead Azure & Dynamics Architect

Group - Strategy & Solutions

M: +55 11 96388-0095
***@***.***

www.ctplc.com
________________________________

**Comment by byme8** [comment]
And yes. Version [v3.2.0-preview.1](https://github.com/byme8/ZeroQL/releases/tag/v3.2.0-preview.1) has support for "... on" syntax

**Comment by byme8** [comment]
Version [v3.2.0](https://github.com/byme8/ZeroQL/releases/tag/v3.2.0) has support for the interface.
