### ISSUE TITLE
Union Type support

### ISSUE THREAD

**Issue by magiclingfeng** [byme8/ZeroQL#22]
union type support

which like this in schema.graphql file
union IResponse = Success | Fail

**Comment by byme8** [comment]
Check out [v3.2.0-preview.1](https://github.com/byme8/ZeroQL/releases/tag/v3.2.0-preview.1) for unions support.
Examples can be found [here](https://github.com/byme8/ZeroQL#unions)

**Comment by byme8** [comment]
Have you had a chance to look at it?

**Comment by byme8** [comment]
Version [v3.2.0](https://github.com/byme8/ZeroQL/releases/tag/v3.2.0) has support for the unions.
