### ISSUE TITLE
CancellationToken support on Query and Mutation operations

### ISSUE THREAD

**Issue by be1223** [byme8/ZeroQL#23]
Currently there is no way to way to provide a `CancellationToken` instance to the async operation of invoking a query/mutation operation.

Since the generated client is backed by a regular .Net `HttpClient` then an optional `CancellationToken` should be accepted and forwarded to the request issued by the underlying client.

The general pattern is to declare a cancellationToken parameter on the method and set it to `default` so invoking a query could look something like this:

``` csharp
var httpClient = new HttpClient();
httpClient.BaseAddress = new Uri("http://localhost:10000/graphql");

var client = new TestServerGraphQLClient(httpClient);

using CancellationTokenSource cts = new(); 

var response = await client.Query(static o => o.Me(o => new { o.Id, o.FirstName, o.LastName }), cts.Token);
```

**Comment by byme8** [comment]
Version [v3.2.0](https://github.com/byme8/ZeroQL/releases/tag/v3.2.0) has support for the cancelation tokens.
