### ISSUE TITLE
Prefer Internal over Public for accessibility of generated types

### ISSUE THREAD

**Issue by be1223** [byme8/ZeroQL#26]
I'm using ZeroQL generated types in a nuget package which I am mapping to other user-defined types via another Models package.

For this reason I would like to have the ZeroQL generated types be declared as `Internal` so that these types are restricted to the assembly performing the mapping and not publicly exposed. 

Currently I have to manually change all of the `public` types to `internal` manually and this change is lost each time the tool is run.

Perhaps it could be an `--accessibility` flag that's passed to the tool which defaults to `public` for backwards compatibility

**Comment by byme8** [comment]
@be1223, checkout the [v3.3.3-preview.6](https://github.com/byme8/ZeroQL/releases/tag/v3.3.3-preview.6).
Now you can control it via `` --visibility `` option:
``` bash
dotnet zeroql generate  -s ./schema.graphql -n TestServer -o ./Generated/GraphQL.g.cs --visibility internal
```

**Comment by byme8** [comment]
Also, now it is possible to do it inside the configuration file.
``` bash
dotnet zeroql config init
dotnet zeroql generate -c ./zeroql.json
```
The `` zeroql.json `` may look like that:
``` json
{
  "$schema": "https://raw.githubusercontent.com/byme8/ZeroQL/main/schema.verified.json",
  "graphql": "./schema.graphql",
  "namespace": "TestServer",
  "clientName": "GraphQLClient",
  "visibility": "Internal",
  "output": "./Generated/GraphQL.g.cs"
}
```
