### ISSUE TITLE
Query not bootstrapped when using named arguments

### ISSUE THREAD

**Issue by be1223** [byme8/ZeroQL#27]
Executing queries using named parameters consistently throws "Query Not Bootstrapped" exceptions, see below snippet.

``` csharp
CancellationTokenSource cts = new();

var result = await gClient.Query(cancellationToken: cts.Token, query: static q => q.Fruits(static f => new { f.Fruit_name }));
```

I've also attached a reproduction below.

[ZeroQLtest.zip](https://github.com/byme8/ZeroQL/files/10507523/ZeroQLtest.zip)

**Comment by byme8** [comment]
Checkout 3.3.4-preview.1 It should work fine.

**Comment by be1223** [comment]
Yep, I can confirm that with the preview version the issue has gone.

Thanks for the quick turnaround
