### ISSUE TITLE
Complex query variables fail to convert

### ISSUE THREAD

**Issue by YaroslavKormushyn** [byme8/ZeroQL#29]
**Describe the bug**
If a query has a complex-type variable as a filter, any initialization of the variable will fail with a compiler-time error: `FailedToConvertPartOfTheQuery	Failed to convert to graphql query`.

**How to Reproduce**
We have a complex schema like this (cut for brevity):
```graphql
type Query {
  getItemsPaged(filter: ItemFilter): ItemPage
}

input ItemFilter {
  ids: [UUID]
  name: String
  pageFilter: PageFilter
}

input PageFilter {
  sort: [String]
  page: Int
  size: Int
}

type ItemPage{
  content: [Item]
  size: Int
  number: Int
  totalElements: Int
  totalPages: Int
  numberOfElements: Int
}

type Item{
  id: UUID!
  class: String
  name: String
  comment: JSON
}
```

Then with the generated client code, the next query won't compile:
```csharp
var httpClient = new HttpClient();
httpClient.BaseAddress = new Uri("http://localhost:10000/graphql");

var client = new TestServerGraphQLClient(httpClient);

var response = await client.Query(static q =>
                q.GetItemsPaged(
                    filter: new ItemFilter { PageFilter = new PageFilter { Page = 0 } },
                    selector: page => new
                    {
                        page.Number,
                        page.TotalPages,
                        Items = page.Content(b => new { Id = b.Id, Name = b.Name, Comment = b.Comment }),
                    })));
```

**Expected behavior**
The query should compile and the filter variable should be correctly added in the GraphQL query.

**Screenshots**
![image](https://user-images.githubusercontent.com/11539004/225354238-087a2d5d-c634-48c4-b6f3-0d0ed4a761ad.png)

**Environment (please complete the following information):**
 - Nuget version [3.4.3]
 - IDE: [VS 2022 Community]
 - .Net Version [net6.0]

**Comment by byme8** [comment]
If you have a complex object, it must be serialized to send a request. If you create it inside the "graphql lambda" ZeroQL doesn't have access to it and can't serialize it before the request. It is a limitation of the current approach.

To make it work you must create an instance before the request and pass it as a variable. Like that:
``` graphql
var httpClient = new HttpClient();
httpClient.BaseAddress = new Uri("http://localhost:10000/graphql");

var client = new TestServerGraphQLClient(httpClient);
var variables = new { Filter = new ItemFilter { PageFilter = new PageFilter { Page = 0 } } };
var response = await client.Query(variables, static (i, q) =>
                q.GetItemsPaged(
                    filter: i.Filter,
                    selector: page => new
                    {
                        page.Number,
                        page.TotalPages,
                        Items = page.Content(b => new { Id = b.Id, Name = b.Name, Comment = b.Comment }),
                    })));
```

**Comment by YaroslavKormushyn** [comment]
Thanks for the clarification! I have seen this in [the example](https://github.com/byme8/ZeroQL#graphql-lambda-syntax), but the variable has been really simple, so I thought it's something else.
I have updated the code and it compiles fine now.
