### ISSUE TITLE
Wrong name case in query

### ISSUE THREAD

**Issue by TheJemy191** [byme8/ZeroQL#34]
Is that expected behavior?

**Describe the bug**
The query that is constructed from my code does not have the right case for the name. They are always lower case.

**Expected behavior**
The constructed query uses the real type not the lower case one.

```csharp
var response = await client
.Query(static c => c.QueryClient(null, null, null, null, c => new { c.Name , cars = c.Cars(null, null, null, c => c.Brand) }));
```
Schema
```graphql
type Client {
  id: ID!
  name: String! // for testing if making it lowercase in the schema work
  Cars(filter: CarFilter first: Int offset: Int): [Car!]
  CarsAggregate(filter: CarFilter): CarAggregateResult
}

type Car {
  id: ID!
  Brand: CarBrand!
  Owners(filter: ClientFilter order: ClientOrder first: Int offset: Int): [Client!]
  OwnersAggregate(filter: ClientFilter): ClientAggregateResult
}
```
```
query { queryClient(filter: null, order: null, first: null, offset: null) { name cars(filter: null, first: null, offset: null) { brand }  } }
Error: Cannot query field "cars" on type "Client". Did you mean "Cars"?
```

**Environment (please complete the following information):**
 - Nuget version [3.5.0]
 - IDE: [VS]
 - .Net Version [7.0.103]

**Additional context**
I'm using Dgraph cloud as my GraphQL provider.

**Comment by byme8** [comment]
It is a bug. During the generation, it converts everything to a lowercase. I will have a look.

**Comment by byme8** [comment]
@TheJemy191 checkout v3.5.1-preview.1 the issue should be fixed.
