### ISSUE TITLE
Defined Scalars that return JSON Array from the API throw a JsonException

### ISSUE THREAD

**Issue by Stephen-Meyerhofer** [byme8/ZeroQL#36]
**Describe the bug**
A scaler "JSON" is defined in the API which throws an exception `System.Text.Json.JsonException: The JSON value could not be converted to Test.GraphQL.JSON` at

```
   at System.Text.Json.Utf8JsonReader.GetString()
   at ZeroQL.ZeroQLScalarJsonConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
```

**How to Reproduce**
Define a GraphQL schema with a field as a custom JSON scalar. Return a JSON Array such as `[{"foo": "bar"}]` in that field.

**Expected behavior**
Parse the API's JSON Array result and store it in the `public sealed record JSON : ZeroQLScalar` type.

**Additional context**
As a workaround I did the following hack.

JSONJsonConverter.cs
```
public class JSONJsonConverter : JsonConverter<JSON>
{
    public override JSON? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = JsonElement.ParseValue(ref reader);

        var scalar = new JSON
        {
            Value = value.ToString(),
        };

        return scalar;
    }

    public override void Write(Utf8JsonWriter writer, JSON value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.Value);
    }
}
```

GraphQL.g.cs
```
    internal static class JsonConvertersInitializers
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        public static void Init()
        {
            global::ZeroQL.Json.ZeroQLJsonSerializersStore.Converters[typeof(global::Test.GraphQL.JSON)] = new JSONJsonConverter();
            // global::ZeroQL.Json.ZeroQLJsonSerializersStore.Converters[typeof(global::Test.GraphQL.JSON)] = new ZeroQLScalarJsonConverter<global::Test.GraphQL.JSON>();
```

**Comment by Stephen-Meyerhofer** [comment]
This works for my use case, however I am concerned it will not work with all APIs. For example, AWS calls their scalar AWSJSON. In theory one could make any arbitrary name for a scalar and return JSON data in that field.

Perhaps revert to the Scalar Json Converter and add some data detection to determine if the data is a string or JSON.

For the time being, I no longer need to hack the generated code. Thank you.

**Comment by byme8** [comment]
I have plans to improve the scalars so you can ship them as a separate Nuget package. It will solve cases when there are lots of providers that think differently.
