### ISSUE TITLE
Code Analyzer fails on unrelated code

### ISSUE THREAD

**Issue by solartechnologies** [byme8/ZeroQL#44]
**Describe the bug**
A code analyser is causing "FailedToConverPartOfTheQuery: Failed to convert to graphql query: {0}" to be raised for an interface that defines a _Query_ method but has no relation to the GraphQL implementation. the method is defined blow as 
`Task<PartialResult<Item>> Query(string id, bool inc, int limit)`

The method is part of a database database interface.

**Expected behavior**
Unless the method is part of a ZeroQL generated class/interface then the analyzer should not raise an error.

**Environment (please complete the following information):**
ZeroQL - 3.6.2.0

**Comment by byme8** [comment]
Can you provide an example of how to reproduce it? I have tried but without any success.

**Comment by solartechnologies** [comment]
Here is a short console app that replicates the issue.
This is occurring for both .NET6 & .NET7 frameworks

```
public class Program
{
    public static async Task Main()
    {
        var client = new ZeroQLClient(new HttpClient());
        IParser parser = new Parser();

        var result = parser.Query("locationId", false, 1);
    }
}

public interface IParser
{
    Task<object> Query(string locationId, bool incremental, int limit);
}

public class Parser: IParser
{
    public Task<object> Query(string locationId, bool incremental, int limit)
    {
        return (Task<object>)Task.CompletedTask;
    }
}
```

This is the error that my visual studio 2022 IDE raises

![image](https://github.com/byme8/ZeroQL/assets/12893874/0e43be5e-0637-49ac-8f13-6c3693e111d1)

**Comment by byme8** [comment]
I managed to reproduce the issue inside VS. However, it works fine in Rider. I will have a look.

**Comment by byme8** [comment]
Checkout v4.1.0-preview.4. The issue should be fixed.
