### ISSUE TITLE
Custom scalars

### ISSUE THREAD

**Issue by lukemurray** [byme8/ZeroQL#45]
Is there a way to define custom scalars? A simple mapping would be fine

I.e. map a gql defined scalar `Date` to dotnet `DateTime`.

Also, we have a scalar defined `Point` and it just returns the json of the point `{x: 1, y: 1}`. It would be good to be able to map that to a C# class

```cs
public class Point {
  public int X { get; set; }
  public int Y { get; set; }
}
```

I couldn't find anything in the documentation about this. And the generated scalars just store the returned string value.

Thanks

**Comment by byme8** [comment]
At the moment, there is no way to define your own. I will have a look at it.

**Comment by lukemurray** [comment]
I do this in a similar library I made by just a simple mapping  - was looking to move to this as it is similar and you've implemented the tool and auto generation on build which is what I wanted to have :)

**Comment by lukemurray** [comment]
Thanks, this does look like it will do we we need. I'll give it a try and let you know of any issues.

Thanks
