### ISSUE TITLE
Add .netstandard 2.1 compatibility

### ISSUE THREAD

**Issue by JuanuMusic** [byme8/ZeroQL#46]
**Is your feature request related to a problem? Please describe.**
I need to be able to use this under Unity. From what I've seen the best way to do it is by supportiong .netstandard 2.1 which has all the APIs

**Describe the solution you'd like**
Implement .netstandard 2.1 as a target framework 

**Additional context**
I have started with this work. I will be posting the branch or possible PRs to tackle this if accepted.

**Comment by byme8** [comment]
I have been thinking about it, and it would be tricky to do.

At the moment, ZeroQL relays on module initializers, records, CallerArgumentExpression. Official they available staring from .Net6+. They are ways to tinker with, but I may not work at all.

**Comment by JuanuMusic** [comment]
I'm actually dealing with those issues.
Ill post a PR when stuff is working and we can keep the discussion from that!
