### ISSUE TITLE
Nullable properties of input arguments lead to NullReferenceException in generated code

### ISSUE THREAD

**Issue by macgyver2k** [byme8/ZeroQL#48]
Running with **4.1.0-preview.2** on **dotnet 7.0**  i am having an issue with the following input type. Both fields are nullable/optional. The server would expect one of them to be provided:

```graphql
input MonitorRelateToOneForCreateInput {
  create: MonitorCreateInput
  connect: MonitorWhereUniqueInput
}
```

The generated code treats both of them as required and tries to get the values of the fields, even if they can be null. This leads to a `System.NullReferenceException`

![image](https://github.com/byme8/ZeroQL/assets/12629897/087d3b3e-72a7-4079-8590-78f898cdfe93)
![image](https://github.com/byme8/ZeroQL/assets/12629897/1da74514-4c01-48b1-bb47-7ba256106ace)

It should be possible to send input objects with nullable properties.

**Comment by byme8** [comment]
I will have a look

**Comment by byme8** [comment]
Checkout v4.1.0-preview.4. The issue should be fixed.

**Comment by macgyver2k** [comment]
Thank you very much. Works perfectly!
