### ISSUE TITLE
Custom scalar types using built-in types

### ISSUE THREAD

**Issue by jenschude** [byme8/ZeroQL#53]
**Is your feature request related to a problem? Please describe.**

The `Int` type for GraphQL may not be sufficient and one would like to support a wider range. Also sometimes you may want to map a scalar just to some builtin type.

```
schema {
  query: Query
}
  
type Query {
  bigNumber: Long!,
  bigDecimal: BigDecimal!,
  locale: Locale!
}

"Represents a 64 bit number"
scalar Long

"Represents an arbitrary big decimal number e.g. decimal type"
scalar BigDecimal

"Represents an IETF language tag https://en.wikipedia.org/wiki/IETF_language_tag"
scalar Locale
```

For now we would have to create a Wrapper class to support this custom scalar. 

**Describe the solution you'd like**

It would be a nice feature to just map this scalar to a built-in type

```
  "scalars": {
    "Long": "long",
    "BigDecimal": "decimal",
    "Locale": "string"
  }
```

**Comment by jenschude** [comment]
Just took another look. Yes for Long it's working out of the box. But when mapping `BigDecimal` to `decimal` it will be generated as

```
public global:: decimal bigDecimal { get; set; }
```

Locale has to be implemented explicitly or suffers from the same issue when trying to map it as a string

```
public global::example.Locale? locale { get; set; } 
public global:: string locale { get; set; } 
```

So being able to explicitly map a value to a primitive type it would make things easier.

**Comment by byme8** [comment]
Tried with
``` json
  "scalars": {
    "BigDecimal": "System.Decimal",
    "Locale": "System.String"
  }
```
Compiles as expected

**Comment by jenschude** [comment]
Oh man. True that. Sometimes it's just simpler than one thinks.
