### ISSUE TITLE
Custom scalars for uuid with Hasura

### ISSUE THREAD

**Issue by BradenCooney** [byme8/ZeroQL#55]
**Is your feature request related to a problem? Please describe.**
We have added a scalar to the zeroql.json file that looks like:
`"scalars": {
      "uuid": "System.Guid"
      }
`
Which works fine when returning a uuid through a query. However, our problem arises when we try to issue a mutation like a delete request and the query it generates looks like:
`"mutation ($id: UUID!) { deleteObject(id: $id) { id } }"`
Unfortunately, Hasura doesn't understand UUID when it is all caps. All it will understand is uuid. The error is:
`Message "variable 'id' is declared as 'UUID!', but used where 'uuid!' is expected"`

**Describe the solution you'd like**
We would like to be able to use the System.Guid for the scalar if possible.

**Describe alternatives you've considered**
We have tried using our own converter for the uuid, but have not had any luck getting rid of the Value property whenever the uuid is Read. Our output is always ` "id": { "Value": "dda0d58b-f90e-421a-ba8a-92381272abf8" } ` instead of our goal of ` "id": "dda0d58b-f90e-421a-ba8a-92381272abf8" `

**Additional context**

**Comment by byme8** [comment]
I will think about how to support your use case. Meanwhile, it can be done via custom JSON serializer:
```  csharp

public static class Module
{
    [ModuleInitializer]
    public static void Initialize()
    {
        ZeroQL.Json.ZeroQLJsonSerializersStore.Converters[typeof(uuid)] = new uuidConverter();
    }
}

public class uuidConverter : JsonConverter<uuid>
{
    public override uuid? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.String)
        {
            return new uuid(reader.GetString()!);
        }
        else
        {
            throw new NotImplementedException();
        }
    }

    public override void Write(Utf8JsonWriter writer, uuid value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.Value);
    }
}
```

**Comment by byme8** [comment]
Checkout 5.0.0-preview.8. 

Now you can set custom scalar:
``` json 
"scalars": { 
    "uuid": "System.Guid" 
} 
```
Write the folowing C# query:
``` csharp
var guid = Guid.NewGuid();
var response = await client.Mutation(m => m.Add(guid));
```
To get the following GraphQL query:
``` graphql
mutation ($guid: uuid!) { add(uuid: $guid)}
```

**Comment by richarddavenport** [comment]
@byme8 Thank you for your tremendous support!
