### ISSUE TITLE
Compatability with numeric IDs

### ISSUE THREAD

**Issue by eaglemc** [byme8/ZeroQL#57]
I'm connecting to a server that returns IDs as numbers instead of strings
```js
{
  "data": {
    "info": {
      "id": 55131,
      "name": "Something Descriptive"
    }
  }
}
```
This appears to be a violation of the [GraphQL specification](https://spec.graphql.org/October2021/#sec-ID), but it's out of my control.

It sounds like the Newtonsoft Json parser might be ok with it, but System.Text.Json throws an exception that it can't convert a number to a string.
This can be handled with a change to ZeroQL.Runtime/Schema/ID.cs such as
```cs
    public override ID? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
	// New: Handle non-strings
        if (reader.TokenType == JsonTokenType.Number)
        {
            var strValue = System.Text.Encoding.UTF8.GetString(reader.ValueSpan);
            return new ID(strValue);
        }
        // Existing: Handle strings
        var value = reader.GetString();
        if (value is null)
        {
            return null;
        }

        return new ID(value);
    }
```

**Comment by byme8** [comment]
Can you provide the GraphQL schema for your case? I want to see how it is defined. It may help with understanding how to handle it.

**Comment by eaglemc** [comment]
Retrieved with
```
zeroql schema pull --url https://api.start.gg/gql/alpha --headers Authorization="Bearer [secret]"
```
[schema_graphql.txt](https://github.com/byme8/ZeroQL/files/11858103/schema_graphql.txt)

Thanks.

**Comment by byme8** [comment]
As workaround you can override scalar `` ID `` with `` int `` like that:
``` json
  "scalars": {
    "ID": "System.Int32"
  }
  ```
  It will replace all `` ID `` as `` int `` and serialization should work fine.
  Meanwhile I will think how to manage it.

**Comment by eaglemc** [comment]
That's a good workaround, thanks.

**Comment by byme8** [comment]
Version 5.0.0 has improvements for scalars. Now you can override it:
``` jsoin
 "scalars": {
    "ID": "System.Int32"
  }
```
and then during the request, it will properly detect the types.
Schema:
``` graphql
type Mutation {
    add(id: ID!): ID!
}
```

Request:
``` csharp
var id = 10;
var response = await zeroQLClient.Mutation(m => m.Add(id));
// mutation ($id: ID!) { add(id: $id)}
```

Because numeric IDs are not supported by official GraphQL spec, I suppose it would be good enough. What do you think?
