### ISSUE TITLE
Generated File produces Compiler Error CS0542

### ISSUE THREAD

**Issue by i20033** [byme8/ZeroQL#59]
**Describe the bug**
The Code-Generation can produce a class that contains a field with the name of the class.
That leads to Compiler Error CS0542 (member names cannot be the same as their enclosing type)

**How to Reproduce**
I testet ZeroQL with the public GraphQL API at "https://spacex-production.up.railway.app/".
After generating, the GraphQL.g.cs contained the class Address, that lead to the error:
[System.CodeDom.Compiler.GeneratedCode ( "ZeroQL" ,  "4.1.0.0" )]
public class Address
{
    [ZeroQL.GraphQLFieldSelector("address")]
    [JsonPropertyName("address")]
    public string? Address { get; set; }

    [ZeroQL.GraphQLFieldSelector("city")]
    [JsonPropertyName("city")]
    public string? City { get; set; }

    [ZeroQL.GraphQLFieldSelector("state")]
    [JsonPropertyName("state")]
    public string? State { get; set; }
}

**Screenshots**
![image](https://github.com/byme8/ZeroQL/assets/123317357/a8c22462-4520-4898-8391-67b53e41c9b1)

**Environment (please complete the following information):**
 - Nuget version 4.1.0
 - IDE: VS 2022
 - .Net Version 7

**Comment by byme8** [comment]
This issue is fixed in 5.0.0-preview.4. 

Duplicate for #54
