### ISSUE TITLE
Is it possbile to generate queries from "query" definitions?

### ISSUE THREAD

**Issue by En3Tho** [byme8/ZeroQL#64]
Hello @byme8 !
Besides main server file I have lots of small graphql client files which usually consist of something like:
```graphql
query QueryName($queryParams) {
  actualQueryToCall($queryParams) {
    ...thingsToReturn
  }
}
```

Can this lib auto-generate those? Or I can only do this manually? Also, the same question about fragment, mutation etc

**Comment by byme8** [comment]
If you want to generate a wrapper for your existing GraphQL queries that were written via GraphQL syntax use [StrawberryShake](https://chillicream.com/docs/strawberryshake/v13/get-started/console)

The ZeroQL allows you to write GraphQL queries with C# that's all. It doesn't generate queries from GraphQL files.

**Comment by En3Tho** [comment]
I see. I just tried StrawberryShake and it just produces invalid 43mb file with almost 700k locs. This is utterly deranged.

I also tried `@graphql-codegen/c-sharp` npm package and as anything that comes from garbage script ecosystem it doesn't work either.

Your library is the only one that just works so I guess I'm sticking with it.
Can you give some pointers on how I can translate graphql query/mutation/fragments using your library? As far as I can see the transformation can be done, it's just that spec file needs to be parsed again so types can be checked.

I believe something like extension methods to a Query/Mutation types could be generated.
Also, as your library is already supporting fragments, I think it's possible to translate gql fragments definitions too.

**Comment by byme8** [comment]
Your example:
``` graphql
query QueryName($queryParams) {
  actualQueryToCall($queryParams) {
    ...thingsToReturn
  }
}
```
It would look like that:
``` csharp
var client = new YourZeroQLClient(httpClient);
var queryParams = // some value
var response = await client.Query("QueryName", q => q.ActualQueryToCall(queryParams, o => o.ToThingsToReturn()))

// ...
public static class ThingsToReturnExtensions
{
    public static SomeReturnType ToThingsToReturn(this QueryType value)
    {
        return new SomeReturnType(value.Id, value.Name);
    }
}
```
The `` YourZeroQLClient `` is the client name specified during the generation. Basically, that's all.

**Comment by En3Tho** [comment]
Thanks. I should have said automatically*. It's just there are so many of these queries that I'd rather tinker with your library and possible do some pr if successful than write all that by hand.

**Comment by byme8** [comment]
Oh, you meant automatically.

Potentially you could create a new CLI or extend [the ZeroQL CLI tool](https://github.com/byme8/ZeroQL/tree/main/src/ZeroQL.CLI) that will parse existing graphql files with [graphql parser](https://github.com/graphql-dotnet/parser) and then generate calls for the "presumably existing" ZeroQL client.

In theory, it should not require any type of information — just translation from raw GraphQL string to raw C# string. However, there are lots of places where something can go wrong.

**Comment by byme8** [comment]
To encapsulate the query you can use [GraphQL request syntax](https://github.com/byme8/ZeroQL#graphql-request-syntax). 

However, here comes another issue. You encapsulate the query and because of it can not return the anonymous type. As a result, you need to generate stub classes to map results to. The StrawberryShake does it.

**Comment by En3Tho** [comment]
I see. Thank you for the insights.

**Comment by byme8** [comment]
> how to send custom headers with the request? From the code I see, custom QueryPipeline should be created?

The client constructor requires the HTTP client. You can set any headers to this HTTP client at any moment or you can implement `` IHttpHandler `` to intercept the HTTP call and add modify it.

**Comment by byme8** [comment]
[Here](https://github.com/byme8/ZeroQL/blob/main/src/ZeroQL.Runtime/HttpHandler.cs) you can find the example for `` IHttpHandler ``. It is a new feature and doesn't have documentation yet.
