### ISSUE TITLE
Nullability issue with struct types in the generated client

### ISSUE THREAD

**Issue by alfa-carinae** [byme8/ZeroQL#65]
**Describe the bug**
I have a scalar `Date` defined in my GraphQL schema. I have a query defined in the schema that returns a (nullable) list of `Date`s. I noticed that Date is internally mapped to the `DateOnly` C# struct and so, the generated method for the said query returns `DateOnly?[]?`. However in the generated code, the method returns a property of the type `DateOnly[]`, which causes a compilation error since it is of a struct type and cannot be converted to `DateOnly?[]`.

**How to Reproduce**
- Have a scalar `Date` defined in the schema.
- Have a query in the schema that returns `[Date]`.
- The generated client code fails to compile.

**Expected behavior**
The query method should return the struct array properly.

**Environment (please complete the following information):**
 - ZeroQL library and tools versions [5.0.0]
 - .NET version [7.0.202]

**Comment by byme8** [comment]
Checkout 6.0.0-preview.2. The issue should be fixed. 

Also, pay attention that 6.0.0+ has changed the initial configuration on setup. It may potentially break the previous configuration. More info [here](https://github.com/byme8/ZeroQL/wiki/Initial-setup).

**Comment by alfa-carinae** [comment]
Will check the changes in initial configuration. Thanks for the quick response!
