### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by GautierT** [byme8/ZeroQL#7]
Hi. 
When I try to add ZeroQL Nuget on Visual Studio I have this error : 

`Could not install package 'ZeroQL 1.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	`

I'm new to C# et .NET dev so any guidance will be much appreciated ;)

Thanks.

**Comment by byme8** [comment]
This library utilizes features from net6.0, such as CallerArgumentExpression.
As a result, it is not compatible with the .Net Framework.
