### ISSUE TITLE
Introspection failed on missing directives fields

### ISSUE THREAD

**Issue by elad-aharon** [byme8/ZeroQL#71]
**Describe the bug**
I'm trying to use zeroQL to query my GraphQL server. I followed the [setup](https://github.com/byme8/ZeroQL#how-to-setup) and failed running schema introspection. The errors I'm getting are: `input:1: Cannot query field "onField" on type "__Directive"` and same goes for `onFragment` & `onOperation` fields. I found out that those 3 fields were deprecated in the [GraphQL spec](https://github.com/graphql/graphql-spec/pull/152) in favor to `locations`. Doing the same introspection query and replace those 3 fields with `locations` works as expected.

**How to Reproduce**
Install any version of [gqlgen](https://github.com/99designs/gqlgen) as a GraphQL server, run it locally and try zeroQL introspection with:
`dotnet zeroql schema pull --url http://localhost:10000/graphql`

**Expected behavior**
I expected schema introspection to work w/o errors, or at least give me the option to support the new introspection schema (with `locations`). 

**Screenshots**
This is ZeroQL 2nd introspection query which fails:
```
query introspection_phase_2 {
  schema: __schema {
    queryType {
      name
    }
    mutationType {
      name
    }
    types {
      ...FullType
    }
    directives {
      name
      description
      args {
        ...InputValue
      }
      onField
      onFragment
      onOperation
    }
  }
}

fragment FullType on __Type {
  kind
  name
  description
  fields(includeDeprecated: true) {
    name
    description
    args {
      ...InputValue
    }
    type {
      ...TypeRef
    }
    isDeprecated
    deprecationReason
  }
  inputFields {
    ...InputValue
  }
  interfaces {
    ...TypeRef
  }
  enumValues(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
  }
  possibleTypes {
    ...TypeRef
  }
}

fragment InputValue on __InputValue {
  name
  description
  type {
    ...TypeRef
  }
  defaultValue
}

fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
          }
        }
      }
    }
  }
}
```

ZeroQL get `422 unprocceable entity` HTTP Error.

**Environment:**
 - Nuget package version 6.0.0
 - IDE:  VS Code
 - .Net Version 6.0.400

**Additional context**
- My GraphQL server is running on [GO gqlgen](https://github.com/99designs/gqlgen) lib.

**Comment by byme8** [comment]
I will have a look, but I am not sure about the fix. The ZeroQL is using HotChocolate.Utilities.Introspection library to introspect the schema. If it doesn't have any way to enable compatibility then we need to look for workaround.

**Comment by elad-aharon** [comment]
@byme8 Thanks for replying!

I found out [this issue](https://github.com/ChilliCream/graphql-platform/pull/618) on HotChocolate.
That led them to [this PR](https://github.com/ChilliCream/graphql-platform/issues/652) for supporting new spec with `locations`.

Looks like we only need to set `HasDirectiveLocations` feature on somehow
https://github.com/ChilliCream/graphql-platform/blob/8f25944c40fab0d4dd54bb2ba28cb4c7a4d2c961/src/Stitching/Stitching/Introspection/IntrospectionClient.cs#L128

but from their code looks like it should be set based on `intospection_phase_1` query. seems like it's not your issue I'll take it with them. 

Thanks

**Comment by elad-aharon** [comment]
closing for now
