### ISSUE TITLE
Error Query is not bootstrapped in Blazor Razor file

### ISSUE THREAD

**Issue by sabuydee** [byme8/ZeroQL#72]
**Describe the bug**
error `Query is not bootstrapped.` in blazor project when using lambda syntax
![image](https://github.com/byme8/ZeroQL/assets/10388591/33c32dc6-5d47-4dca-988d-7fc757f9409d)

**How to Reproduce**
1. run project from this repository [https://github.com/sabuydee/ZeroQL-Lab](url)
2. go to fetch data page and see error

**Screenshots**
code in `ZeroQLLab/Pages/FetchData.razor`
<img width="892" alt="image" src="https://github.com/byme8/ZeroQL/assets/10388591/508b43b5-46b5-4cf7-a45e-e00f99720f2e">

**Environment (please complete the following information):**
 - Nuget package version [All version)
 - IDE: VS, VS for Mac, Rider, VS Code
 - .Net Version 6.0.400

**Comment by byme8** [comment]
Looks like there is nothing I can do. The modern razor files are processed via source generator. The resulted C# then executed at runtime. As a result, other source generators do not have access to generated code. [Here more information about it](https://andrewlock.net/using-source-generators-with-blazor-in-dotnet-6/#source-generators-can-t-use-the-output-of-other-source-generators)

You can try to legacy razor processing by adding 
``` xml
<UseRazorSourceGenerator>false</UseRazorSourceGenerator>
```
or move ZeroQL query to a independent C# service.

**Comment by giusepanzuto** [comment]
It seems that a work around for the issue is to use a partial class for the razor component. For example, using Index.razor for markup and Index.razor.cs for code.

G.
