### ISSUE TITLE
Parameter name casing incorrect

### ISSUE THREAD

**Issue by andriy-tsvikla** [byme8/ZeroQL#74]
**Describe the bug**
Incorect casing in query parameter

**How to Reproduce**
this is part of graphql schema with query i am trying to use
```
type Query {
  """
  Get a Action from the database by its ID/primary key
  """
  action_by_pk(ActionID: Int!): Action
}
```

**Expected behavior**

Call from code 
`  var response = await client.Query(o => o.Action_by_pk<Action>(actionId, x => new Action`
Query parameter "ActionID" should start with Upper letter.
```
query ($actionId: Int!) {
                            action_by_pk(ActionID:$actionId )
```

**Screenshots**

![zeroql](https://github.com/byme8/ZeroQL/assets/17903457/2fc21733-86a4-4b4c-8d96-673d75040a31)

**Environment (please complete the following information):**
 - Nuget package version [6.0.0]
 - IDE: [VS]
 - .Net Version [6.0.400]

**Additional context**
But query parameter "ActionID" starts with lower case letter.
Part of the query retrieved from "GraphQLQueryStore<Query>.Query" dictionary entry 

`query ($actionID: Int!) { action_by_pk(actionID: $actionID) { `

c# method definition from zeroql.json.g.cs in obj/ZeroQL
```
        [JsonPropertyName("action_by_pk")]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Action? __Action_by_pk { get; set; }

        [ZeroQL.GraphQLName("action_by_pk")]
        public T? Action_by_pk<T>([ZeroQL.GraphQLType("Int!")] int ActionID = default !, Func<Action, T> selector = default !)
        {
            return __Action_by_pk is null ? default : selector(__Action_by_pk);
        }
```

Not sure if its bug or i am missing some configuration. 
Thanks

**Comment by byme8** [comment]
Checkout v6.1.0-preview.2. The issue should be fixed.

**Comment by andriy-tsvikla** [comment]
contents of nuget build folder for preview package is different than for 6.0.0
.nuget\packages\zeroql\6.1.0-preview.2\build\net6.0
when i deleted conents of this folder and replaced with contents if 6.0.0 build folder it worked

**Comment by byme8** [comment]
I will have a look. However, the Nugget ZeroQL has no reference to
NewtonSoft. It is only ZeroQL.Cli that has the reference.

**Comment by andriy-tsvikla** [comment]
![1](https://github.com/byme8/ZeroQL/assets/17903457/8ab14266-8b86-4acd-a329-f4044815aacd)
![2](https://github.com/byme8/ZeroQL/assets/17903457/a3730e6d-5a62-4b11-aa96-31ddc5bd108c)

**Comment by andriy-tsvikla** [comment]
anyway the casing seems to be fixed so i close this issue and open new one
