### ISSUE TITLE
Select all the properties at once

### ISSUE THREAD

**Issue by RASK18** [byme8/ZeroQL#76]
It would be very useful to have some way to select all the properties at once, maybe with an .All() or leaving the method empty (marked in green)

And I don't know if it is possible, but it would also be great if it was not necessary to declare the names of the anonymous type, it is a bit redundant (marked in red).

![image](https://github.com/byme8/ZeroQL/assets/16093842/11a6d7b8-c3b4-4538-bcde-ba3476889d9b)

I have just discovered this project and I love it <3
PD: Sorry for my English, it is not my native language

**Comment by byme8** [comment]
I have been thinking about such feature and it is not align well with the general graphql mindset.
For example, in your case you wrote a query like 
``` graphql
query {
   media  {
     id
     title {
        english
    }
  }
}
```
It works fine and you get pressingly what you requested. No additional cost associated with over-fetching. However,
later on the schema may change and media would have new field `` body ``. If it is implemented correctly, for original query nothing changes. Performance is not affected, the public contract is not effected.

In case when you can write query like that:
``` graphql
query {
   media  {
    *
  }
}
```
You will get performance a hit immediately and the public contract would change. So, I decided to keep ZeroQL implementation aligned with the global graphql semantic.
