### ISSUE TITLE
Unable to set alias, so mutation fails if same mutation operation is used multiple times

### ISSUE THREAD

**Issue by noah-integrityinspired** [byme8/ZeroQL#77]
**Describe the bug**
Say I want to issue a mutation where I use the same mutation operation twice, but I have it aliased.
```graphql
mutation {
  first: updateUsers(where: {...}, _set: {...}){...}
  second: updateUsers(where: {...}, _set: {...}){...}
}
```

However I can't seem to make ZeroQL apply the alias; instead it generates something like this:
```graphql
mutation {
 updateUsers(where: {...}, _set: {...}){...}
 updateUsers(where: {...}, _set: {...}){...}
}
```
When I use code like this:
```csharp
await client.Mutation(variables, static (variables, mutation_root) => new
{
    first = mutation_root.UpdateUsers(...),
    second = mutation_root.UpdateUsers(...)
}
```

**Expected behavior**
Is it possible to add aliases with zeroQL? I looked through the wiki, issues, and interface and I was unable to find a way to accomplish this. 

**Environment (please complete the following information):**
 - Nuget package version [6.0.0]
 - IDE: Rider
 - .Net Version: 7

**Comment by byme8** [comment]
At the moment that queries is not supported by ZeroQL. I had plans to work on it together with the defer support, but at the moment it is not clear when it happen.

**Comment by noah-integrityinspired** [comment]
@byme8 got yeah; thank you for prompt reply!
