### ISSUE TITLE
Query example for queries with pagination

### ISSUE THREAD

**Issue by everscope** [byme8/ZeroQL#79]
Hello,

Could you add example of ZeroQl query for query with pagination to documentation? I can not find any examples in documentation

Thank you!

**Comment by byme8** [comment]
The pagination implementation depends more on the server side. The ZeroQL works with whatever server exposes.
For example, server graphql schema with pagination:
``` graphql
schema {
  query: Queries
}

type Queries {
  users(page: Int!, size: Int!, sorting: UserSorting!, order: SortOrder!): [User!]
}

enum UserSorting {
  FirstName,
  LastName
}

enum SortOrder {
  DESC,
  ASC
}

type User {
  id: Int!
  firstName: String!
  lastName: String!
}
```

The ZeroQL call:
``` csharp
var page = 0;
var size = 10;
var top10Users = await client.Query(q => q.Users(page, size, UserSorting.FirstName, SortOrder.Desc,  u => u.Id))
```

I wrote the example without IDE, so there can be syntax issues.

**Comment by everscope** [comment]
I have this query
```
query {
  MyType(first: 10) {
    edges {
      cursor
      node {
        id
        name
      }
    }
  }
}
```

And I want to rewrite it with ZeroQl, but I cannot select MyType directly, because it is inside node 
<img width="525" alt="image" src="https://github.com/byme8/ZeroQL/assets/79381961/58f1b372-b5ad-4f86-abac-ceeb1e15a5b1">

so I suppose it should be like this, but it does not work and I can not find similar examples in google 
<img width="543" alt="image" src="https://github.com/byme8/ZeroQL/assets/79381961/66473032-bd8a-422c-bb50-2d020bb334e5">
<img width="915" alt="image" src="https://github.com/byme8/ZeroQL/assets/79381961/e12b01cb-4a60-4d67-8c02-3135238ee728">

**Comment by byme8** [comment]
Can you post the full schema?

**Comment by everscope** [comment]
Sure!
Example schema looks like this:
```graphql
type Query {
  users(first: Int after: String last: Int before: String): UsersConnection
}

type UsersConnection {
  pageInfo: PageInfo!
  edges: [UsersEdge!]
  nodes: [User!]
}

type UsersEdge {
  cursor: String!
  node: User!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}
```
That's default schema for paging using connection's

https://graphql.org/learn/pagination/#pagination-and-edges
https://chillicream.com/docs/hotchocolate/v13/fetching-data/pagination

**Comment by byme8** [comment]
Oh, I see it. It is a completely different problem than I thought at the beginning.

The anonymous classes support syntax like that `` new { o.Id } `` but they expect you to define the property when you call the method like that `` new { Edges = o.Edges() } 

So, define the property:
``` csharp
var siteLocationsQuerry = _cloudServiceGraphQlClient
         .Query(sitelocationsFilter, static (i, q) =>
              q.SiteLocations(
                   where: i.Where, order: null, first: 1000,
                   selector: n => new 
                   {
                       Edges = n.Edges(e => e.Node(n => n.Id))
                   }));
```

**Comment by everscope** [comment]
Oh, now I see🥲 Thank you!
