### ISSUE TITLE
support extensions

### ISSUE THREAD

**Issue by omurphy-repay** [byme8/ZeroQL#8]
A GraphQL server reponds to:
`{"query": "query { ping }"}`
with:
```
{ "data": { "ping": "pong" },
  "extensions": { "requestId": "488baa5c-be04-49ac-957f-ba739096b229" }
}
```
When sending the same query request to that server using ZeroQL, the response is:
```
{
    "query": "query { ping}",
    "data": { "ping": "pong"},
    "errors": null
}
```
The **extensions** key is missing from the response, making ZeroQL unsuitable for some integrations.

**Comment by byme8** [comment]
What graphql server do you use? I have been playing around with HotChocolate and could not figure out how to put some values into the extensions field to test the fix.

**Comment by byme8** [comment]
Checkout v2.0.0
