### ISSUE TITLE
Customize naming

### ISSUE THREAD

**Issue by clintsinger** [byme8/ZeroQL#80]
I'm just getting started with ZeroQL and I noticed that the interface types don't start with an `I` which is pretty typical C# syntax for interfaces.   

I realize it isn't for everyone but it would be great if there was a setting that let you decide whether interfaces are prefixed with or without the `I`.   Perhaps some way just to set prefix and post fix rules generally?

**Comment by byme8** [comment]
I have been thinking about something like that. I have decided to keep whatever is defined in the GraphQL schema to avoid misunderstanding while comparing the generated code and the initial GraphQL files.

If the library starts moving in this direction, it will raise questions about other options. The C# and the GraphQL paradigms have many small differences that can be adjusted like that.
