### ISSUE TITLE
ZeroQL.GraphQueryError

### ISSUE THREAD

**Issue by cskuba** [byme8/ZeroQL#85]
**Describe the bug**
Hi,
But I'm struggling with following problem:

```
var result = await _apiClient.Query(q => q.Pages(1, null, null, null, null, order, p => p.Nodes(pg => 
new Page
{
    Id = pg.Id,
    Published = pg.Published.HasValue ? pg.Published.Value.DateTime : null,
    Slug = pg.Slug,
    PageTemplateId = pg.PageTemplateId,
    Blocks = pg.Blocks(pb => new PageBlock
    {
        BlockId = pb.BlockId,
        PageId = pb.PageId,
        SortOrder = pb.SortOrder
    })
})); 
```
And I get this error:
![image](https://github.com/byme8/ZeroQL/assets/110968241/8bdedbf6-d2e5-443f-8186-593eb8ef60a5)

I know it's caused by Blocks = pg.Blocks(pb => new Api.CoreModels.Page.PageBlock........ part but I cant figure it out why, what could be a problem. I attach file with definition of classes: 
[resultClasses.txt](https://github.com/byme8/ZeroQL/files/13561682/resultClasses.txt)

It works fine, if I use anonymous type or generated classes like:

```
var result = await _apiClient.Query(q => q.Pages(1, null, null, null, null, order, p => p.Nodes(pg =>
                     new
                     {
                         pg.Id,
                         pg.Published,
                         pg.Slug,
                         pg.PageTemplateId,
                         Blocks = pg.Blocks(pb => new
                         {
                             pb.BlockId,
                             pb.PageId,
                             pb.SortOrder,
                          })
                     }
    )));

```
```
var result = await _apiClient.Query(q => q.Pages(1, null, null, null, null, order, p => p.Nodes(pg =>
    new ZeroQL.Client.Page
            {
                Id = pg.Id,
                Published = pg.Published,
                Slug = pg.Slug,
                PageTemplateId = pg.PageTemplateId,
                __Blocks = pg.Blocks(pb => new ZeroQL.Client.PageBlock
                {
                    BlockId = pb.BlockId,
                    PageId = pb.PageId,
                    SortOrder = pb.SortOrder
                })
            }  )));
```

**The GraphqQL schema that fails**
[schema.txt](https://github.com/byme8/ZeroQL/files/13561455/schema.txt)

**Environment (please complete the following information):**
 - Nuget package version [6.1.0]
 - IDE: [Microsoft Visual Studio Community 2022 (64-bit) v17.8.0]
 - .Net Version [8.0.100]

**Comment by byme8** [comment]
For me it reports compilation error in Rider IDE on MacOS. What is expected behavior:
<img width="1028" alt="image" src="https://github.com/byme8/ZeroQL/assets/5927686/f56843a6-c33e-44c0-a2d9-5e3983bd2293">

Everything inside the query lambda is converted to the raw GraphQL query at compilation time. As a result, only selected set of the C# features is supported. The ternary operator is not supported and in my case the analyzer reports the error.

In your case, it doesn't report the error for some reason. That's weird. I will check VS v17.8.0 latter today.

**Comment by cskuba** [comment]
Ok, Thanks for your quick support, you're right. Problem was caused by ternary operator in Published section. It was my first thought, cause I've seen similar error elsewhere during the testing. But my Visual studio is  behaving completely weird since last update, so after several attemps (trial-error) I've become convinced it caused by Blocks = pg.Blocks(....) part.
Anyway thank you for your efforts and sorry for bugging you about it.
