### ISSUE TITLE
 ZeroQL.CLI not found when building on GitHub Actions

### ISSUE THREAD

**Issue by DaveRMaltby** [byme8/ZeroQL#87]
**Describe the bug**

Just upgraded to the latest major version of ZeroQL and am using a local file of my GraphQL schema for client generation.  I followed the instructions for [How to setup](https://github.com/byme8/ZeroQL?tab=readme-ov-file#how-to-setup) and everything works fine on my devbox.  It is only when my GitHub Actions pipeline runs, does it fail with the following error:

```
/home/runner/.nuget/packages/zeroql/6.1.1/build/net7.0/ZeroQL.props(13,9): warning MSB3073: The command "dotnet zeroql --version" exited with code 1. [/home/runner/work/ZeroQL_CLI_not_found/ZeroQL_CLI_not_found/Integration.BaseSchema.ClientCodeGeneration/MockDB.Integration.BaseSchema.ClientCodeGeneration.csproj]
/home/runner/.nuget/packages/zeroql/6.1.1/build/net7.0/ZeroQL.props(21,9): error : ZeroQL CLI could not be found. Please install it before proceeding. [/home/runner/work/ZeroQL_CLI_not_found/ZeroQL_CLI_not_found/Integration.BaseSchema.ClientCodeGeneration/MockDB.Integration.BaseSchema.ClientCodeGeneration.csproj]
```

I have even tried to add:

`dotnet tool install --global ZeroQL.CLI` 

In the same build step [here](https://github.com/Servant-Software-LLC/ZeroQL_CLI_not_found/blob/master/.github/workflows/LinuxBuild.yml#L26C9-L26C9), which the build log indicates that it was installed successfully, but still the:

`dotnet build --configuration $BuildConfiguration`

Fails with the same error.

**How to Reproduce**

You can run either the Linux or Windows build pipelines located at https://github.com/Servant-Software-LLC/ZeroQL_CLI_not_found/actions.  They both have the same issue.

**Expected behavior**

Generated g.cs file.  Like seen on devbox:

```
1>------ Build started: Project: MockDB.Integration.BaseSchema.ClientCodeGeneration, Configuration: Debug Any CPU ------
1>v6.1.1
1>./obj/ZeroQL/config.zeroql.json.g.cs
1>Output path: C:\Dev\TestPrograms\ZeroQL_CLI_not_found\Integration.BaseSchema.ClientCodeGeneration\obj\ZeroQL\config.zeroql.json.g.cs
1>The source code is up-to-date with graphql schema. Skipping code generation.
1>MockDB.Integration.BaseSchema.ClientCodeGeneration -> C:\Dev\TestPrograms\ZeroQL_CLI_not_found\Integration.BaseSchema.ClientCodeGeneration\bin\Debug\net7.0\MockDB.Integration.BaseSchema.ClientCodeGeneration.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

```

**The GraphqQL schema that fails**

In GitHub Actions, it never gets to the point of trying to interogate  the schema.  There is no schema failure on devbox.

**Screenshots**

**Environment (please complete the following information):**
 - Nuget package version [6.1.1]
 - IDE: [GitHub Actions]
 - .Net Version [7.0.404]

**Additional context**
I've created a simple [publicly available repo](https://github.com/Servant-Software-LLC/ZeroQL_CLI_not_found) that reproduces the issue.  Feel free to manipulate it however or fork it.  Thanks!

**Comment by DaveRMaltby** [comment]
Here is [my workaround attempt](https://github.com/Servant-Software-LLC/ZeroQL_CLI_not_found/compare/master...WorkaroundAttempt) that sets the ZeroQL.CLI tool's PATH for GitHub Actions, but still it [fails in the same manner](https://github.com/Servant-Software-LLC/ZeroQL_CLI_not_found/actions/runs/7238952059/job/19720319851).

**Comment by byme8** [comment]
Before you do `` dotnet build ``. Call `` dotnet tool retore ``. It will restore the tools defined in tool manifest.
Here, I created the sample project https://github.com/byme8/ZeroQLGitHubActions/blob/main/.github/workflows/main.yml

**Comment by DaveRMaltby** [comment]
Thank you, Stanislav!!  Glad it was merely just my issue.  Your suggestion fixed the issue.
