### ISSUE TITLE
Assigning To Class/Record Fails to Query Properties

### ISSUE THREAD

**Issue by nolanblew** [byme8/ZeroQL#90]
**Describe the bug**

Following the tutorial while implementing my own data, I'm not able to query and place the result in a new class or record, but the query works fine when I place it in an anonymous object.

**How to Reproduce**
### Working Example
```c#
var response = await client.Query(
    o => o.SearchProfileByUsername(first: 1, username: username, selector: pi => pi.Nodes(profile => new {
        Id = profile.Id,
        Name = profile.Name
    }))
);
```

This results in the following query with an appropriate response:
```json
{"variables":{"username":"test"},"query":"query ($username: String!) { searchProfileByUsername(first: 1, username: $username) { nodes { id name __typename }  } }"}
```
Note how we are querying in the `nodes` for `id`, `name`, along with `__typename`.

### Not Working Example
Now let's say I have this record:
```c#
public record Profile(string Id, string Name);
```
_Note: the same result can be obtained in a class instead of a record_

And then I attempt to create and inject from ZeroQL:
```c#
var response = await client.Query(
    o => o.SearchProfileByUsername(first: 1, username: username, selector: pi => pi.Nodes(profile => new Models.Profile(
        Id: profile.Id,
        Name: profile.Name
    )))
);
```

This is now what is sent:
```json
{"variables":{"username":"nblew"},"query":"query ($username: String!) { searchProfileByUsername(first: 1, username: $username) { nodes {  __typename }  } }"}
```

Note that the _only_ property being queried by ZeroQL in the "node" is `__typename`, but not `id` or `name`. This results in those properties always being null.

<img width="299" alt="image" src="https://github.com/byme8/ZeroQL/assets/1565705/5ea582bf-464d-49bd-a025-c87ab6130206">

**Expected behavior**

I would expect that accessing a property will always request it in the graphql query regardless if the target object is an anonymous object or a well-defined class

**Environment (please complete the following information):**
 - Nuget package version [6.1.1]
 - IDE: [VS 2022 17.8.6, VS Code]
 - .Net Version [8.0]
 - App Type: Console

**Comment by byme8** [comment]
I have tried replicating your example, and it works fine for me.
Can you create a small repository with the issue so I can pull and check it?

Here is my query:
``` csharp
namespace expZeroQL
{
    public record User(ID Id, string FirstName);
}

// ...

var response = await client
.Query(q => q
    .Me(o => new expZeroQL.User(Id: o.Id, FirstName: o.FirstName)));
```

**Comment by nolanblew** [comment]
Ok update - After some digging it looks like the example I gave didn't give the issue in question, and I was on the wrong track with thinking it had to do with classes/record (although an anonymous type throws an exception while a record just gives a warning when the issue happens). The issue has to do with attempting to transform a portion of the query into a property.

I [opened a new issue](#91) with the problem in question.
