### ISSUE TITLE
Cannot Populate Object with Static Values or Linq Code

### ISSUE THREAD

**Issue by nolanblew** [byme8/ZeroQL#91]
I cannot populate a model in the query using LINQ code, or even static values (such as `null`) without the query just ignoring _all_ properties I wanted.

Example:
```c#
// Models
public record MyUser(string Id, string Name, string Username, MyLogin? LastLogin = null);
public record MyLogin(string Time, bool Success);
```

```c#
// Program.cs
var request = await client.Query(q => q.GetByUsername(username, user => new MyUser(
    Id: user.Id,
    Name: user.Name,
    Username: user.Username,
    LastLogin: user.LoginAttempts(first: 1, login => new MyLogin(
        Time: login.Time,
        Success: login.Success
    )).FirstOrDefault()
)));
```
This throws an exception:
```
An exception of type 'System.NullReferenceException' occurred in ZeroQL.Runtime.dll but was not handled in user code: 'Object reference not set to an instance of an object.'
   at ZeroQL.ID.op_Implicit(ID id)
```

When inspecting the request, it completely ignores _all_ properties requested and looks like this:
```json
{"variables":{"username":"john"},"query":"query ($username: String!) { GetByUsername(username: $username) {  } }"}
```

This is the same if I attempt to set `LastLogin: null`.

However, if I ommit the `LastLogin` alltogether (and let the default `null` value in the parameter take over), it works as expected with the request looking like:
```json
{"data":{"GetByUsername":{"id":"1","name":"John Doe","username":"john"}}}
```

I also have tested and it also works if the `MyUser` model accepts a `ICollection<MyLogin>`, and I don't attempt to transform it at all. However in my real project would prefer not to do this as we already have our domain models set up, and the main benefit of using ZeroQL is the Query model generation (I would not like to have to create my own models just to satisfy the query - I am already doing that in the base GraphQL library and it's a pain when you have 100+ models).

If there is already a way around this, perhaps updating the setup instructions and/or the wiki would be awesome.

## Github Repo
I created a repo you can clone and download here: https://github.com/nolanblew/TestQLClient

## Environment
**Environment (please complete the following information):**
 - Nuget package version [6.1.1]
 - IDE: [VS 2022 17.8.6, VS Code]
 - .Net Version [8.0]
 - App Type: Console

** Other context **
This was misdiagnosed and accidently opened an issue describing the wrong problem: https://github.com/byme8/ZeroQL/issues/90

**Comment by byme8** [comment]
Checkout v6.2.0-preview.2.

There was an issue with error reporting. Now your query would fail to build because of `` .FirstOrDefault() ``
``` csharp
var request = await client.Query(q => q.GetByUsername(username, user => new MyUser(
    Id: user.Id,
    Name: user.Name,
    Username: user.Username,
    LastLogin: user.LoginAttempts(first: 1, login => new MyLogin(
        Time: login.Time,
        Success: login.Success
    )).FirstOrDefault() // <= compilation error here
)));
```

The goal is to keep "compatibility"/balance between the raw GraphQL and C# queries. The `` FirstOrDefault() `` is definitely a thing that GraphQL does not natively support. So, it is not allowed because it alters the behavior of the query. 
At the same, things like `` new User(o.Id, o.Name) `` are allowed because it doesn't alter the behavior of the query and helps to streamline the development.
