### ISSUE TITLE
Selector lambda as an expression for more efficient transfer to/from the server

### ISSUE THREAD

**Issue by NickStrupat** [byme8/ZeroQL#93]
**Is your feature request related to a problem? Please describe.**
It would be nice if the `selector` func was an expression, so that only the property names in the selector are part of the generated query.

**Describe the solution you'd like**
Instead of the selector being `Func<Person, T>`, it would be `Expression<Func<Person, T>>`. Additionally, the code that generates a query body would, instead of including all property names, include only the only included in the selector.

**Describe alternatives you've considered**
I've heard it's possible to extract property names from inside a `Func<T, R>`, but it's basically a hack. Expressions are supported.

**Comment by byme8** [comment]
I am not sure what you mean. It is already a "compile-time expression." The source generator analyzes the `` Func<Person, T> `` body and generates a query that would be used in runtime. Can you provide an example of use case?

**Comment by byme8** [comment]
> I've heard it's possible to extract property names from inside a Func<T, R>, but it's basically a hack. Expressions are supported.
Yeah, basically, my implementation is a hack that works in compile time and costs nothing in runtime. With expressions, everything would happen in runtime, and performance would be much worse.

**Comment by NickStrupat** [comment]
Oh I see. You're right. Maybe I misunderstood a log I was looking at. I thought I was seeing that ZeroQL was doing a `select *` kind of thing. Thank you for the quick support!
