### ISSUE TITLE
Shorthand for returning a fully hydrated model

### ISSUE THREAD

**Issue by NickStrupat** [byme8/ZeroQL#96]
**Is your feature request related to a problem? Please describe.**
Returning a fully-hydrated model requires specifying each property. It might be good to allow automatic hydration.

**Describe the solution you'd like**
Basically, removing this constraint:

`ZQL0005: Open lambda like 'o => o' are not allowed. Use a lambda like 'o => new { o.Id }' or define a fragment.`

And adding support for `o => o`, where it retrieves all the properties without having to specify them in code like this

```csharp
o => new Model { PropA = o.PropA, PropB = o.PropB, ... }
```

**Comment by byme8** [comment]
I don't plan to add it. Here is why https://github.com/byme8/ZeroQL/issues/76

**Comment by NickStrupat** [comment]
Thank you for the kind and prompt response!
