### ISSUE TITLE
ZeroQL CLI not working from Azure Devops pipelines

### ISSUE THREAD

**Issue by devl-up** [byme8/ZeroQL#98]
**Describe the bug**

When my project is build from the Azure Devops Pipeline, the following errors shows up

`/home/AzDevOps/.nuget/packages/zeroql/6.1.1/build/net7.0/ZeroQL.props(13,9): warning MSB3073: The command "dotnet zeroql --version" exited with code 150`

Locally, everything works fine.

I do have a step in my pipeline that restores the project's tools

![image](https://github.com/byme8/ZeroQL/assets/28202491/84e4f34e-b884-499e-890f-8c41f66a6c2e)

Which works

![image](https://github.com/byme8/ZeroQL/assets/28202491/79d4ecf8-4dc2-449d-98b8-d3df31863653)

Here's the step which fails

![image](https://github.com/byme8/ZeroQL/assets/28202491/36f7a32e-faba-4b50-a93e-3f3a4bff5126)

The weird thing is that it is not the default "tool XXX not found" error from dotnet itself, so I'm pretty sure he actually calls & finds the tool.

Another thing that is weird is that my project is running & building in .NET 8 (which he finds), and when installing the tool he seems to do it under a 7.0 folder, which u can see in the last picture (also saying I'm missing the 7.0 SDK)

EDIT:

Installing the 7.0 alongside the 8.0 SDK in the pipeline seemed to fix the issue, the question is if this is expected behavior then ?

**Comment by byme8** [comment]
6.1.1 doesn't support net8.0. Try the v6.2.0-preview.4. It has support for .net8.0.

I have started the build for 6.2.0. In half an hour, the proper non-preview version will be ready.

**Comment by devl-up** [comment]
@byme8 alright thanks a lot will close this one !
